; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino, espidf
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv ; แนะนำใช้ Partition ขนาดใหญ่เนื่องจากตัวโปรแกรม VPN จะใช้พื้นที่ Flash สูงกว่าปกติ
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_SUPPORT
    -DCONFIG_LITTLEFS_PAGE_SIZE=256
    -Icomponents/littlefs/include
    -Icomponents/littlefs/src/littlefs

lib_deps =
    LittleFS
    FS
    PicoMQTT
    Adafruit GFX Library
    Adafruit SSD1306